Major rework of the sbt-dotty plugin for cross-compilation support
lampepfl/sbt-dotty pull request #4
Opened 2017-04-28 08:21 UTC by smarter

This PR depends on the unmerged https://github.com/lampepfl/dotty/pull/2312 and won't pass the CI until it is merged and a new nightly is published.

- The plugin can now be used to cross-compile between Scala 2 and Dotty:
Just enabling the plugin will not change anything in your build, you
need to set scalaVersion to a Dotty version (starting with "0.") to
enable Dotty support. This also works `crossScalaVersions`.

- The plugin now works with the newly-published bootstrapped version of
dotty

- The plugin now uses `scalaBinaryVersion` 0.1 instead of 2.11, dotty
still supports depending on 2.11 artifacts but you need to use
`withDottyCompat` (see README.md).

2017-04-28 08:23 UTC, smarter commented
Review by @felixmulder (I don't have the rights to add a reviewer in this repo :/)

2017-04-28 08:23 UTC, smarter commented
/cc @sjrd If you have time, it'd be nice if you could double-check this.

2017-04-28 11:50 UTC, felixmulder commented
@smarter - rights should be fixed now.

2017-04-28 11:52 UTC, felixmulder commented
Currently fails with: 

```
[info] [error] (*:update) sbt.ResolveException: unresolved dependency: ch.epfl.lamp#dotty_0.1;0.1.1-bin-20170427-fa13f8d-NIGHTLY: not found
```

2017-04-28 12:01 UTC, smarter commented
Yes, that's normal, https://github.com/lampepfl/dotty/pull/2312 needs to be merged, the nightly build script adjusted, and a new nightly published, before the CI pass.

2017-04-28 12:09 UTC, felixmulder approved these changes
Otherwise LGTM, excited to get this in!

2017-04-28 12:09 UTC, felixmulder commented on README.md
> +works because Dotty is currently retro-compatible with Scala 2.x.
2.11.x?

2017-04-28 12:09 UTC, felixmulder commented on README.md
> +**NOTE**: Dotty's retro-compatibility with Scala 2.x will be dropped before
"will **most likely** be dropped" - IMHO

2017-04-28 12:09 UTC, felixmulder commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
> +       *  NOTE: Dotty's retro-compatibility with Scala 2.x will be dropped before
2.11.x here too, if you agreed with the above

2017-04-28 12:09 UTC, felixmulder commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
>        println(s"Latest Dotty nightly build version: $latest")
Weren't you the one to say not to use println with sbt? Or maybe that was only in `build.sbt`...

2017-04-28 12:12 UTC, sjrd requested changes
A few things that can be improved.

Also, since now the plugin doesn't do any modifications on its own (all its settings are triggered only when `scalaVersion` is independently set to `0.1...`, it would be safe and convenient to automatically trigger the `AutoPlugin`. You can do that with:
```scala
override def trigger = allRequirements
```
in the `AutoPlugin`.

That way, users don't even have to specify `enablePlugins(DottyPlugin)`. All they need is the `addSbtPlugin` and the `scalaVersion :=`.

2017-04-28 12:12 UTC, sjrd commented on README.md
> +scalaVersion := dottyLatestNightlyBuild.get
This does not look like a safe default for reproducible builds.

2017-04-28 12:12 UTC, sjrd commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
> +	}
You've got tabs in here, and that's pretty awful ;)

2017-04-28 12:12 UTC, sjrd commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
> +       *      libraryDependencies += "a" %% "b" % "c"
You should use
```
{{{
libraryDependencies += "a" %% "b" % "c"
}}}
```
in Scaladoc so that this is properly formatted as code.

2017-04-28 12:12 UTC, sjrd commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
>        resolvers += Resolver.typesafeIvyRepo("releases")
Ideally this should also be protected by `if (isDotty.value)`. Something like
```scala
resolvers ++= {
  if (isDotty.value)
    Seq(Resolver.typesafeIvyRepo("releases"))
  else
    Nil
}
```

2017-04-28 12:20 UTC, felixmulder commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
> +       *      libraryDependencies += "a" %% "b" % "c"
Guillaume's been spoiled with dottydoc having markdown 😉

2017-04-28 12:32 UTC, smarter commented on README.md
> +works because Dotty is currently retro-compatible with Scala 2.x.
No, we might switch to 2.12 at some point, e.g. dotty 0.1 with 2.11.x and dotty 0.2 with 2.12.x

2017-04-28 12:33 UTC, smarter commented on README.md
> +**NOTE**: Dotty's retro-compatibility with Scala 2.x will be dropped before
No, I think this is pretty sure.

2017-04-28 12:33 UTC, smarter commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
>        println(s"Latest Dotty nightly build version: $latest")
Yes, I just don't know how to fix it in a def, also this isn't code I wrote.

2017-04-28 12:34 UTC, smarter commented on src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala
> +	}
Yeah, I copy-pasted it from sbt which does that, will fix.

2017-04-28 13:17 UTC, smarter commented on README.md
> +scalaVersion := dottyLatestNightlyBuild.get
I'll put a real number here once we get a working nightly build for this.

2017-04-28 13:27 UTC, smarter commented
Thanks for the review @sjrd !

2017-04-28 14:35 UTC, olafurpg commented
PS. From my experience, setting the `scalaVersion` alone is not enough, you also need to configure `scalacOptions`. Most scalac options like `-Xfatal-warnings` are invalid in dotc. I would recommend to provide an optional setting that does something like

```scala
scalacOptions := CrossVersion.partialVersion(scalaVersion.value) match {
  case Some((0, _)) => Seq("-language:Scala2")
  case _ => scalacOptions.value
}
```
that users can mix into their project settings.

2017-04-28 15:04 UTC, smarter commented
@olafurpg Feel free to make a PR for that improvement, I don't have time to work on that now.

2017-05-01 20:30 UTC, smarter commented
https://github.com/lampepfl/dotty/pull/2312 has been merged so the tests now pass, thanks everyone for your comment! @felixmulder Could you publish `0.1.0-RC4`?

2017-05-01 20:30 UTC, merged

2017-05-01 20:38 UTC, felixmulder commented
@smarter: :shipit:  it's on its way to maven